CREATE SCHEMA IF NOT EXISTS tww_hydr;

GRANT ALL ON ALL TABLES IN SCHEMA tww_hydr TO tww_user;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tww_hydr TO tww_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA tww_hydr GRANT ALL ON TABLES TO tww_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA tww_hydr GRANT ALL ON SEQUENCES TO tww_user;